import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/app/providers";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Syntax Society Studio",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/assets/SyntaxSociety.ico", type: "image/png", sizes: "32x32" },
      { url: "/assets/SyntaxSociety.ico", type: "image/png", sizes: "16x16" },
    ],
    apple: "/assets/SyntaxSociety.png",
  },
};

// Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/SyntaxSociety.png" type="image/png" sizes="32x32" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
